### ISSUE TITLE
Submit kubectl-dpod to the Krew Index

### ISSUE THREAD

**Issue by aslafy-z** [jpriebe/kubectl-pod-inspect#1]
For an enhanced usability, I'd recommend you to create a Krew Index entry for `kubectl-dpod`.
Here's link to the documentation: https://krew.sigs.k8s.io/docs/developer-guide/release/new-plugin/

**Comment by jpriebe** [comment]
Done.  I've renamed the plugin "pod_inspect", which I don't like due to its verbosity, but I didn't think that "dpod" would work with the krew naming convention.

https://github.com/kubernetes-sigs/krew-index/pull/1021
